config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  # has_many :doses, dependent: :destroy, validate: false
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    # byebug
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:destroy]

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">Mr. Cocktail</a> -->
  <%= link_to 'Mister Cocktail', root_path, class: "navbar-brand" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <!-- <%= link_to 'New Cocktail', new_cocktail_path, class: "nav-link" %>
      <%= link_to 'Back to home', cocktails_path, class: "nav-link" %> -->
      <%= link_to new_cocktail_path, :class=> "nav-link" do %>
          <i class="fa fa-plus-circle" aria-hidden="true" target="_blank"></i>
      <% end %>
      <%= link_to root_path, :class=> "nav-link" do %>
          <i class="fas fa-home" aria-hidden="true" target="_blank"></i>
      <% end %>
    </div>
  </div>
</nav>

app/views/cocktails/index.html.erb
<%= render "nav" %>

<div class="container">
  <h4 class="createBtn"><%= link_to "Create a cocktail", new_cocktail_path %></h4>
  <div class="row row-cols-1 row-cols-md-3">
    <% @cocktails.each do |cocktail| %>
    <div class="col mb-4">
      <div class="card">
        <img src="<%= cocktail.image %>" class="card-img-top cocktail-img" alt="...">
        <div class="card-body cocktail-body">
          <h5 class="card-title"><%= cocktail.name %></h5>
          <%= link_to 'See more', cocktail %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/cocktails/new.html.erb
<%= render "nav" %>

<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :image %>
    
    <%= f.button :submit, class: 'btn btn-success' %>
  <% end %>
</div>

<div class="container container-center">
  <%= link_to 'Back to home', cocktails_path, class: "btn btn-primary" %>
</div>

app/views/cocktails/show.html.erb
<%= render "nav" %>

<div class="container container-show">
  <div class="row">
    <div class="col-6 mb-4">

      <div class="card bg-light">
        <div class="card-body cocktail-body">
          <h1 class="mb-3"><%= @cocktail.name %></h1>
          <img src="<%= @cocktail.image %>" class="card-img-top cocktail-img" alt="...">
        </div>
      </div>
    </div>
    <div class="col-lg-6 mb-4">
      <div class="card bg-light">
        <div class="card-body cocktail-body">
          <h1 class="mb-4">Ingredients</h1>

          <% @cocktail.doses.each do |dose| %>
          <div class="ingredient-display d-flex row">
            <div class="col-6">
              <h5 class="card-title"><%= dose.ingredient.name %></h5>
            </div>
            <div class="col-6">
              <%= link_to 'Delete', dose_path(dose),  method: :delete %>
            </div>
          </div>
          <% end %>
          <div class="show-btn">
            <%= link_to 'Add some doses', new_cocktail_dose_path(@cocktail) %>
          </div>
          <div class="show-btn">
            <%= link_to 'Back to home', cocktails_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.button :submit, 'Submit This Form', class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>